### ISSUE TITLE
[WFRP4e System] Players get Error: User (name) lacks permission to update ChatMessage

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#1106]
When rolling a test as the defender in an opposed check, players will get an error message similar to
Error: User Player2 lacks permission to update ChatMessage [TZlEGP5hRCYGG8mo]

Console output for the error above:

Uncaught (in promise) Error: User Player2 lacks permission to update ChatMessage [TZlEGP5hRCYGG8mo]
    at ServerDatabaseBackend._updateDocuments (file:///E:/Foundry%20Virtual%20Tabletop/resources/app/dist/database/backend/server-backend.mjs:1:3039)
    at runNextTicks (node:internal/process/task_queues:61:5)
    at processImmediate (node:internal/timers:437:9)
    at async Semaphore._try (file:///E:/Foundry%20Virtual%20Tabletop/resources/app/common/utils/semaphore.mjs:99:17)

Reproducible - got the above in a fresh world, only Core Content module enabled. A PC actor was made, and a creature taken from the Bestiary to attack the PC. No console error on the GMs side, no error when a player is the attacker.

Console errors after the 1st were somewhat different (1st was not expandable):

Uncaught (in promise) Error: User Player2 lacks permission to update ChatMessage [8v6LaxlYFtTabWB4]
    at ServerDatabaseBackend._updateDocuments (/E:/Foundry%20Virtual%20Tabletop/resources/app/dist/database/backend/server-backend.mjs:1:3039)
    at async Semaphore._try (/E:/Foundry%20Virtual%20Tabletop/resources/app/common/utils/semaphore.mjs:99:17)
_handleError @ foundry.js:2253
(anonymous) @ foundry.js:2237
value @ socket.js:307
value @ socket.js:237
T.emit @ index.js:143
value @ manager.js:200
T.emit @ index.js:143
value @ index.js:105
value @ manager.js:192
T.emit @ index.js:143
value @ socket.js:323
T.emit @ index.js:143
value @ transport.js:99
value @ transport.js:92
ws.onmessage @ websocket.js:76
await in ws.onmessage (async)
colorWinnerAndLoser @ opposed-wfrp4e.js:247
computeOpposeResult @ opposed-wfrp4e.js:113
await in computeOpposeResult (async)
handleOpposed @ test-wfrp4e.js:425
roll @ test-wfrp4e.js:103
await in roll (async)
basicTest @ actor-wfrp4e.js:1331
(anonymous) @ actor-sheet.js:693
Promise.then (async)
_onSkillClick @ actor-sheet.js:692
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
<br/>**From**: Fhawkner#1813<br/>foundry: 9.255<br/>wfrp4e: 5.2.0<br/>wfrp4e-core: 2.4.2

**Comment by VeilOfOblivion** [comment]
Probably related: It looks like the error breaks the code to apply damage. You can apply the damage (right clicking on the window and choose the option - it will reduce the wounds) but the dialog never closes and the information about the damage isn't added (e.g. "Damage Applied: 3 (4 TB + 1 AP)". 
If the GM is using the same chat message, it works just fine. So it seems related to the issue

**Comment by moo-man** [comment]
This is fixed in fa4caa90f963469cf7b10d6835bdfc99b026b01a however I was not experiencing the same problems as @VeilOfOblivion 

The message it was trying to update was the opposed start, not the result, and damage still was applied appropriately.
