### ISSUE TITLE
Errors with WFRPTableConfig sheet

### ISSUE THREAD

**Issue by Jagusti** [moo-man/WFRP4e-FoundryVTT#1200]
**Describe the bug**
Template does not show or preserve settings for 
- name, description, icon
- roll formula 
- options to draw with replacement or display roll to chat
- table key, table column

A model validation error is thrown, and sometimes other errors (such as no results available)
Console errors are also thrown (see comments).

**To Reproduce**
1. Either 
  i. Create a new table inside WFRP4e system 6.0.0.9 with a couple of results. 
  ii. Import table, eg, Dark Whispers from GM Toolkit.
2. Open the table if not already open. The name should be a placeholder.
3. Add a name and roll formula
4. Roll (without updating). 
5. Replace the name. Update. Settings are cleared, but the name entered is adopted as the application window title. No error is thrown.

The table is drawn from, but settings are reverted.

Tables behave as expected in DnD5e system. 

**Screenshots**
Using WFRP4e Rolltable sheet
![image](https://user-images.githubusercontent.com/521096/184537966-77f5a6f4-5186-42b4-a2f7-4c3c472b004d.png)

Using native FTT Rolltable sheet
![image](https://user-images.githubusercontent.com/521096/184537744-f8be3c57-8b43-45de-a444-af5ef4177ff0.png)

Settings revert after drawing from table
![image](https://user-images.githubusercontent.com/521096/184538184-5be947b5-b8a6-413d-bb32-e1a9da064de4.png)

Application window title updated
![image](https://user-images.githubusercontent.com/521096/184538414-8ea72d9b-68b3-4e3c-809f-af96e3d30188.png)

**Version Numbers**
Foundry: 10.277
wfrp4e: 6.0.0.9
GM Toolkit v10 development version

**Comment by Jagusti** [comment]
**Console errors**

> foundry.js:55888 Model Validation Errors
> [RollTable.name]: may not be a blank string
> fetch @ foundry.js:55888
> notify @ foundry.js:55815
> error @ foundry.js:55851
> _preUpdateDocumentArray @ foundry.js:12292
> _updateDocuments @ foundry.js:12206
> update @ commons.js:6212
> await in update (async)
> updateDocuments @ commons.js:5567
> update @ commons.js:5664
> _updateObject @ foundry.js:62353
> _onSubmit @ foundry.js:5637
> submit @ foundry.js:5928
> _onRollTable @ foundry.js:62281
> dispatch @ jquery.min.js:2
> v.handle @ jquery.min.js:2

The following error appears with the above
> foundry.js:709 Error: RollTable [9rXQv4uJcQoLBitt] Model Validation Errors
> [RollTable.name]: may not be a blank string
>     at SchemaField._validateType (commons.js:3576:15)
>     at SchemaField.validate (commons.js:3303:37)
>     at RollTable.validate (commons.js:4925:35)
>     at ClientDatabaseBackend._preUpdateDocumentArray (foundry.js:12290:13)
>     at ClientDatabaseBackend._updateDocuments (foundry.js:12206:33)
>     at ClientDatabaseBackend.update (commons.js:6212:24)
>     at async RollTable.updateDocuments (commons.js:5567:23)
>     at async RollTable.update (commons.js:5664:23)
> onError @ foundry.js:709
> _preUpdateDocumentArray @ foundry.js:12293
> _updateDocuments @ foundry.js:12206
> update @ commons.js:6212
> await in update (async)
> updateDocuments @ commons.js:5567
> update @ commons.js:5664
> _updateObject @ foundry.js:62353
> _onSubmit @ foundry.js:5637
> submit @ foundry.js:5928
> _onRollTable @ foundry.js:62281
> dispatch @ jquery.min.js:2
> v.handle @ jquery.min.js:2

Roll Formula is incorrectly cleared, resulting in the following expected error.

> foundry.js:55888 There are no available results which can be drawn from this table.

**Comment by Jagusti** [comment]
No longer an issue with FVTT 10.283 and WFRP4e 6.1.1
