### ISSUE TITLE
[WFRP4e System] [Group Advantage] When combat is over, tokens retain their advantage

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#1251]
When combat is ended, the system removes any remaining advantage from the combat tracker tab. The tokens on the map, however, retain their advantage value. The console throws the following error: 

foundry.js:711 TypeError: Cannot read properties of null (reading 'combatants')
[Detected 1 package: system:wfrp4e]
    at Object.fn (wfrp4e.js:14413:23)
    at #call (foundry.js:688:20)
    at Hooks.callAll (foundry.js:645:17)
    at ClientDatabaseBackend.callback (foundry.js:12745:13)
    at foundry.js:12681:43
    at Array.map (<anonymous>)
    at ClientDatabaseBackend._handleUpdateDocuments (foundry.js:12681:33)
    at ClientDatabaseBackend._updateDocuments (foundry.js:12542:17)
    at async Setting.updateDocuments (commons.js:5674:23)
    at async Setting.update (commons.js:5771:23)
    at async ClientSettings.set (foundry.js:2793:20)
    at async clearCombatantAdvantage (wfrp4e.js:13341:9)

And that's the last of the bugs (for this week)! Sorry about the number of grievances in the past 24 hours. We really love the foundry wfrp4e system, I promise!<br/>**From**: The First#7330<br/>foundry: 10.285<br/>wfrp4e: 6.1.2

**Comment by sladecraven** [comment]
A macro or easy API to add/reduce the group advantages could be great also :) !

**Comment by moo-man** [comment]
@sladecraven I'm not sure I understand exactly what you need, simply changing an actor's advantage will change the group advantage accordingly
