### ISSUE TITLE
[WFRP4e System] Cleared Character sheet

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#1562]
Place container on character in scene. delete container. error is thrown. clears character sheet. I deactivated all modules and still have the same issue.

foundry.js:59187 Error when running effect Armour, please see the console (F12)
fetch @ foundry.js:59187
notify @ foundry.js:59114
error @ foundry.js:59150
runSingleEffect @ wfrp4e.js:7509
(anonymous) @ wfrp4e.js:15808
runEffects @ wfrp4e.js:15800
prepareData @ wfrp4e.js:13075
_safePrepareData @ foundry.js:13264
_initialize @ foundry.js:13089
updateSource @ commons.js:5586
_onUpdateTokenActor @ foundry.js:22434
_onUpdate @ foundry.js:22369
callback @ foundry.js:12823
(anonymous) @ foundry.js:12804
_handleUpdateEmbeddedDocuments @ foundry.js:12804
_updateEmbeddedDocuments @ foundry.js:12672
await in _updateEmbeddedDocuments (async)
update @ commons.js:6795
await in update (async)
updateDocuments @ commons.js:6153
update @ commons.js:6250
deleteActorEmbeddedDocuments @ foundry.js:22244
_deleteEmbeddedDocuments @ foundry.js:12865
delete @ commons.js:6856
await in delete (async)
deleteDocuments @ commons.js:6198
deleteEmbeddedDocuments @ commons.js:6364
deleteEffectsFromItem @ wfrp4e.js:16197
callback @ wfrp4e.js:9882
await in callback (async)
submit @ foundry.js:56403
_onClickButton @ foundry.js:56332
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
wfrp4e.js:7510 Error when running effect Armour - If this effect comes from an official module, try replacing the actor/item from the one in the compendium. If it still throws this error, please use the Bug Reporter and paste the details below, as well as selecting which module and 'Effect Report' as the label.<br/>**From**: Wink88#8871<br/>foundry: 10.291<br/>wfrp4e: 6.5.1<br/>wfrp4e-core: 3.1.1<br/>wfrp4e-wom: 3.0.1<br/>Active Modules: betterroofs, dice-so-nice, levels, lib-wrapper, multilevel-tokens, nations-of-mankind-wfrp4e, one-page-parser, quickscale, scene-backup-tool, settings-extender, simplefog, socketlib, sprite-rotation, the-dwarf-empire-wfrp4e, wall-height, wfrp4-wfrp4e-npc-generator, wfrp4e-character-details, wfrp4e-gm-toolkit, wfrp4e-laws-pet-shoppe, wfrp4e-random-treasure, wfrp4e-unofficial-grimoire

**Comment by Wink8008** [comment]
Additional console log info:

Error: You are accessing PlaceableObject#data which is no longer used and instead the Document class should be referenced directly as PlaceableObject#document.
Deprecated since Version 10
Backwards-compatible support will be removed in Version 12
    at Object.logCompatibilityWarning (commons.js:1692:19)
    at Token.get (foundry.js:24831:23)
    at VisionSource.getVisionSourcePolygonConfiguration (main.js:18:33)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:616:16)
    at 🎁VisionSource.prototype._getPolygonConfiguration#0 (libWrapper-wrapper.js:189:20)
    at VisionSource._createPolygon (foundry.js:48620:57)
    at VisionSource.initialize (foundry.js:49787:21)
    at Token.updateVisionSource (foundry.js:46041:19)
    at Token.updateSource (foundry.js:45977:10)
    at updateTokenSourceBounds (patches.js:256:13)
    at Token.tokenOnUpdate (patches.js:240:5)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:616:16)
    at 🎁CONFIG.Token.objectClass.prototype._onUpdate#0 (libWrapper-wrapper.js:189:20)
    at TokenDocument._onUpdate (foundry.js:12367:38)
    at TokenDocument._onUpdate (foundry.js:22373:18)
    at ClientDatabaseBackend.callback (foundry.js:12823:11)
    at foundry.js:12804:43
    at Array.map (<anonymous>)
    at ClientDatabaseBackend._handleUpdateEmbeddedDocuments (foundry.js:12804:33)
    at ClientDatabaseBackend._updateEmbeddedDocuments (foundry.js:12672:17)
    at async TokenDocument.updateDocuments (commons.js:6153:23)
    at async TokenDocument.update (commons.js:6250:23)
    at async TokenDocument.modifyActorDocument (foundry.js:22120:5)
    at async ActorWfrp4e.updateDocuments (commons.js:6153:23)
    at async ActorWfrp4e.update (commons.js:6250:23)
    at async ActorSheetWfrp4eCreature._onSubmit (foundry.js:5916:7)
    at async ActorSheetWfrp4eCreature.submit (foundry.js:6237:5)
    at async ActorSheetWfrp4eCreature.close (foundry.js:6209:19)
    at async ActorSheetWfrp4eCreature.close (foundry.js:6337:5)

**Comment by Wink8008** [comment]
and a little more console log:

wfrp4e.js:7511 REPORT
-------------------
EFFECT:	Armour
ACTOR:	Orc - E7BiDqsB55BrOQut
ERROR:	TypeError: Cannot read properties of undefined (reading 'getFlag')

**Comment by moo-man** [comment]
Fixed in V11 https://github.com/foundryvtt/foundryvtt/issues/8351
