### ISSUE TITLE
[Core Rulebook] Adding Outlaw Career Loops

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#1577]
When I add the Outlaw career to any token (tried Human and Black Bella), it gets in a loop adding the Hardy trait over and over again.<br/>**From**: eric.c.berg@gmail.com<br/>foundry: 10.291<br/>wfrp4e: 6.5.2<br/>wfrp4e-altdorf: 2.0.2<br/>wfrp4e-core: 3.1.1<br/>wfrp4e-up-in-arms: 3.0.4<br/>Active Modules: dice-so-nice, foundryvtt-simple-calendar, lib-wrapper, popout, token-action-hud, wfrp4e-gm-toolkit, forge-vtt

**Comment by ericcberg** [comment]
Console Log:
Foundry VTT | Created Token with id [O44G64tI3DRj9Vy2] in parent Scene [2HjP1XX54IKTmk2b]
foundry.js:5099 Foundry VTT | Rendering ActorSheetWfrp4eCreature
foundry.js:6887 Foundry VTT | Retrieved and compiled template systems/wfrp4e/templates/actors/creature/creature-sheet.hbs
gm-toolkit.mjs:20 wfrp4e-gm-toolkit |  Human is not in an active encounter in scene Battlemap. No change to Advantage is being made.
text.min.mjs:8 Canvas2D: Multiple readback operations using getImageData are faster with the willReadFrequently attribute set to true. See: https://html.spec.whatwg.org/multipage/canvas.html#concept-canvas-will-read-frequently
t.measureFont @ text.min.mjs:8
25gm-toolkit.mjs:20 wfrp4e-gm-toolkit |  Human is not in an active encounter in scene Battlemap. No change to Advantage is being made.
foundry.js:5099 Foundry VTT | Rendering TokenHUD
foundry.js:6887 Foundry VTT | Retrieved and compiled template templates/hud/token-hud.html
2gm-toolkit.mjs:20 wfrp4e-gm-toolkit |  Human is not in an active encounter in scene Battlemap. No change to Advantage is being made.
commons.js:6946 Foundry VTT | Deleted Token with id [O44G64tI3DRj9Vy2] in parent Scene [2HjP1XX54IKTmk2b]
foundry.js:59187 The key O44G64tI3DRj9Vy2 does not exist in the EmbeddedCollection Collection
fetch @ foundry.js:59187
wfrp4e.js:15094 Something went wrong when adding talent Hardy: Error: The key O44G64tI3DRj9Vy2 does not exist in the EmbeddedCollection Collection
_advanceTalent @ wfrp4e.js:15094
foundry.js:59187 Something went wrong when adding talent Hardy: Error: The key O44G64tI3DRj9Vy2 does not exist in the EmbeddedCollection Collection
fetch @ foundry.js:59187
wfrp4e.js:15094 Something went wrong when adding talent Rover: Error: The key O44G64tI3DRj9Vy2 does not exist in the EmbeddedCollection Collection
_advanceTalent @ wfrp4e.js:15094
foundry.js:59187 Something went wrong when adding talent Rover: Error: The key O44G64tI3DRj9Vy2 does not exist in the EmbeddedCollection Collection
fetch @ foundry.js:59187
wfrp4e.js:15094 Something went wrong when adding talent Strider (any): Error: The key O44G64tI3DRj9Vy2 does not exist in the EmbeddedCollection Collection
_advanceTalent @ wfrp4e.js:15094
wfrp4e.js:15094 Something went wrong when adding talent Trapper: Error: The key O44G64tI3DRj9Vy2 does not exist in the EmbeddedCollection Collection
_advanceTalent @ wfrp4e.js:15094
commons.js:3289 Uncaught (in promise) Error: undefined. The key O44G64tI3DRj9Vy2 does not exist in the EmbeddedCollection Collection
[No packages detected]
    at EmbeddedCollection.get (commons.js:3289:15)
    at ClientDatabaseBackend._preUpdateDocumentArray (foundry.js:12706:26)
    at ClientDatabaseBackend._updateEmbeddedDocuments (foundry.js:12661:33)
    at ClientDatabaseBackend.update (commons.js:6795:33)
    at async TokenDocument.updateDocuments (commons.js:6153:23)
    at async TokenDocument.update (commons.js:6250:23)
    at async TokenDocument.modifyActorDocument (foundry.js:22120:5)
foundry.js:59187 Something went wrong when adding talent Trapper: Error: The key O44G64tI3DRj9Vy2 does not exist in the EmbeddedCollection Collection
fetch @ foundry.js:59187
foundry.js:59187 Something went wrong when adding talent Strider (any): Error: The key O44G64tI3DRj9Vy2 does not exist in the EmbeddedCollection Collection

**Comment by moo-man** [comment]
I cannot reproduce this. I've added the Outlaw career and it all works without issue
![image](https://user-images.githubusercontent.com/28637157/236063875-57cd8dd7-e0b7-436d-9849-9fdb0b23c8f6.png)

**Comment by BoltsJ** [comment]
I ran into a similar issue with an NPC and am able to replicate the issue using a Creature on 7.0.1 with core 4.0.0.

I think it's caused by `findTalent` not checking that the actual item type is talent and so, in this case, the Outlaw career is specifying the Trapper talent, but the item that is retrieved is the Trapper career and so it adds the career item instead of a talent. This surfaced for me after the 4.0.0 core update merged all the item compendiums. I suspect that @ericcberg had the Trapper career imported into their world, leading to the loop since that career also adds the Trapper talent.

I also saw that some talents that have identically named traits will lead to the trait getting added rather than the talent, in my testing Hardy and Night Vision.

![Screenshot from 2023-09-07 22-05-03](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/182554/d3948054-8015-439e-b5a3-759d1fcd7809)

[Screencast from 2023-09-07 21-52-36.webm](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/182554/09260b7d-ca9c-4890-90dd-e810f50afd98)
