### ISSUE TITLE
[WFRP4e System] Character Sheet Breaks

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#1606]
Character Sheet breaks when comabt starts and token moves. In the "Skills" section all digits disappear from the column "Total". All unofficial modules were disabled, only official WFRP modules were enabled.

commons.js:2004 Error: You are accessing EffectWfrp4e#label which has been migrated to EffectWfrp4e#name
Deprecated since Version 11
Backwards-compatible support will be removed in Version 13
    at logCompatibilityWarning (commons.js:1993:19)
    at EffectWfrp4e._logDataFieldMigration (commons.js:8403:14)
    at EffectWfrp4e.get (commons.js:8892:28)
    at wfrp4e.js:9074:57
    at Array.filter (<anonymous>)
    at ActorSheetWfrp4eCharacter._consolidateEffects (wfrp4e.js:9074:27)
    at ActorSheetWfrp4eCharacter.filterActiveEffects (wfrp4e.js:9052:38)
    at ActorSheetWfrp4eCharacter.getData (wfrp4e.js:8786:10)
    at async ActorSheetWfrp4eCharacter.getData (wfrp4e.js:11085:23)
And
 You are accessing EffectWfrp4e#label which has been migrated to EffectWfrp4e#name
Deprecated since Version 11
Backwards-compatible support will be removed in Version 13
    at logCompatibilityWarning (commons.js:1993:19)
    at EffectWfrp4e._logDataFieldMigration (commons.js:8403:14)
    at EffectWfrp4e.get (commons.js:8892:28)
    at get displayLabel [as displayLabel] (wfrp4e.js:712:22)
    at lookupProperty (handlebars.min.js:27:16153)
    at eval (eval at createFunctionContext (handlebars.min.js:29:1808), <anonymous>:17:91)
    at h (handlebars.min.js:27:17870)
    at c (handlebars.min.js:27:6899)
    at Object.<anonymous> (handlebars.min.js:27:7289)
    at Object.c (handlebars.min.js:27:19853)<br/>**From**: Wolenard#9823<br/>foundry: 11.299<br/>wfrp4e: 6.5.5<br/>wfrp4e-altdorf: 2.0.2<br/>wfrp4e-archives1: 2.4.1<br/>wfrp4e-archives2: 3.0.5<br/>wfrp4e-core: 3.1.1<br/>wfrp4e-dotr: 3.0.1<br/>wfrp4e-eis: 3.1.3<br/>wfrp4e-empire-ruins: 3.0.5<br/>wfrp4e-horned-rat: 2.0.1<br/>wfrp4e-middenheim: 2.4.2<br/>wfrp4e-pbtt: 2.2.3<br/>wfrp4e-rnhd: 3.0.5<br/>wfrp4e-starter-set: 3.1.2<br/>wfrp4e-ua1: 3.0.1<br/>wfrp4e-ua2: 2.0.0<br/>wfrp4e-up-in-arms: 3.0.4<br/>wfrp4e-wom: 3.0.2<br/>wfrp4e-zoo: 3.0.0<br/>Active Modules:

**Comment by SimonasBanys** [comment]
#1607 is duplicate, but contains steps to reproduce

**Comment by Wolenard** [comment]
Correct! Steps are these:
1. Select an actor.
2. Add it to the combat
3. Start combat with one or more actors (either PC or NPC)
4. Move a token anywhere.
