### ISSUE TITLE
Deprecation warnings logged in console

### ISSUE THREAD

**Issue by grz0** [moo-man/WFRP4e-FoundryVTT#1652]
**Describe the bug**
Foundry logs about 100 deprecation warnings in a freshly created game world. 

~~~
commons.js:2004 Error: You are accessing EffectWfrp4e#label which has been migrated to EffectWfrp4e#name
Deprecated since Version 11
Backwards-compatible support will be removed in Version 13
    at logCompatibilityWarning (commons.js:1993:19)
    at EffectWfrp4e._logDataFieldMigration (commons.js:8434:14)
    at EffectWfrp4e.get (commons.js:8906:28)
    at WFRP_Utility.runSingleEffect (wfrp4e.js:7536:59)
    at wfrp4e.js:15913:27
    at Array.forEach (<anonymous>)
    at ActorWfrp4e.runEffects (wfrp4e.js:15905:13)
    at ActorWfrp4e._calculateWounds (wfrp4e.js:14654:10)
    at ActorWfrp4e.checkWounds (wfrp4e.js:14542:25)
    at ActorWfrp4e.prepareNonVehicle (wfrp4e.js:13345:10)
~~~

**To Reproduce**
Create a new game world on v11 and launch it.

**Screenshots**
![image](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/3605541/dc378572-5c6e-41c1-b4b8-7e2786bada85)

**Version Numbers**

Foundry: v11 304
wfrp4e: 6.5.9
wfrp4e-core: 3.1.4
wfrp4e-starter-set:  3.1.5
wfrp4e-rnhd: 3.0.7
wfrp4e-altdorf: 3.0.0

**Comment by grz0** [comment]
fixed in v7.0.0
