### ISSUE TITLE
[WFRP4e System] Aura effect being removed incorrectly

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#1999]
the recording includes shows the aura effects being removed incorrectly when a token is moved within an aura.  Their are two auras here overlapped<br/>**From**: steven.evans<br/>foundry: 11.315<br/>wfrp4e: 7.1.4<br/>wfrp4e-core: 5.0.4<br/>Active Modules: filepicker-plus, lib-wrapper, module-credits, socketlib

**Comment by StevenEvans1966** [comment]
Sorry thought I could record the problem here is the test scene (using Core tokens and traits only) and a before and after screen sho.t

[fvtt-Scene-test-IBXVXLgkLSjQk20g.json](https://github.com/moo-man/WFRP4e-FoundryVTT/files/15204950/fvtt-Scene-test-IBXVXLgkLSjQk20g.json)
![image](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/81326195/279c098e-4c2a-4617-a6a8-03818349adfa)
![image](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/81326195/b8b7bf8c-9649-43c0-bc73-4f66da00c740)

**Comment by StevenEvans1966** [comment]
Also found that moving  the Big Daemonette of Slaanesh up results in the following errors

Foundry VTT | Deleted ActiveEffect with id [HbqMfCGjqs2VlQQR] in parent ActorDelta [ywx5YROrcPUyF65k]
foundry.js:68326 undefined id [HbqMfCGjqs2VlQQR] does not exist in the EmbeddedCollectionDelta collection.
fetch @ foundry.js:68326
notify @ foundry.js:68223
error @ foundry.js:68260
_handleError @ foundry.js:3468
(anonymous) @ foundry.js:3450
value @ socket.js:532
value @ socket.js:459
L.emit @ index.mjs:136
(anonymous) @ manager.js:207
Promise.then (async)
it @ websocket-constructor.browser.js:5
value @ manager.js:206
L.emit @ index.mjs:136
value @ index.js:131
value @ manager.js:193
L.emit @ index.mjs:136
value @ socket.js:324
L.emit @ index.mjs:136
value @ transport.js:97
value @ transport.js:89
ws.onmessage @ websocket.js:69
commons.js:8114 Uncaught (in promise) Error: undefined. undefined id [HbqMfCGjqs2VlQQR] does not exist in the EmbeddedCollectionDelta collection.
[No packages detected]
    at EmbeddedCollectionDelta.get (file:///D:/Program%20Files/Foundry%20Virtual%20Tabletop%20v11/resources/app/common/abstract/embedded-collection.mjs:164:36)
    at file:///D:/Program%20Files/Foundry%20Virtual%20Tabletop%20v11/resources/app/dist/database/backend/server-backend.mjs:1:5212
    at Array.map (<anonymous>)
    at ServerDatabaseBackend._deleteDocuments (file:///D:/Program%20Files/Foundry%20Virtual%20Tabletop%20v11/resources/app/dist/database/backend/server-backend.mjs:1:5202)
    at ServerDatabaseBackend.delete (file:///D:/Program%20Files/Foundry%20Virtual%20Tabletop%20v11/resources/app/common/abstract/backend.mjs:182:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Semaphore._try (file:///D:/Program%20Files/Foundry%20Virtual%20Tabletop%20v11/resources/app/common/utils/semaphore.mjs:101:17)
_handleError @ foundry.js:3466
(anonymous) @ foundry.js:3450
value @ socket.js:532
value @ socket.js:459
L.emit @ index.mjs:136
(anonymous) @ manager.js:207
await in (anonymous) (async)
checkAreas @ wfrp4e.js:12376
await in checkAreas (async)
(anonymous) @ wfrp4e.js:23639
#call @ foundry.js:730
callAll @ foundry.js:687
callback @ foundry.js:13738
(anonymous) @ foundry.js:13711
#handleUpdateDocuments @ foundry.js:13711
await in #handleUpdateDocuments (async)
_updateDocuments @ foundry.js:13458
await in _updateDocuments (async)
update @ commons.js:8677
await in update (async)
updateDocuments @ commons.js:8001
updateEmbeddedDocuments @ commons.js:8233
moveMany @ foundry.js:35648
_handleMovement @ foundry.js:1963
(anonymous) @ foundry.js:2082
setTimeout (async)
_onPan @ foundry.js:2082
onDown @ foundry.js:1660
_executeKeybind @ foundry.js:2502
_processKeyboardContext @ foundry.js:2543
_handleKeyboardEvent @ foundry.js:2601
(anonymous) @ foundry.js:2227
commons.js:8807 Foundry VTT | Deleted ActiveEffect with id [7h3dIAL0WNDq1Iju] in parent ActorDelta [uzxKkO6GrLgBIEeO]

**Comment by StevenEvans1966** [comment]
Just tested with 7.2 this issue has not been fixed.  I assume it has been rolled into another task

**Comment by moo-man** [comment]
Yes this wasn't intended to be closed
