### ISSUE TITLE
[WFRP4e System] Unable to apply Damage from Opposed Test

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#2067]
Just start a new world and added 4 characters to learn combat. After having opposed combat rolls, the Apply Damage button doesn't seem to do anything. I see the following error in the console log.

Error in the console:
TypeError: Cannot read properties of undefined (reading 'value')
    at ActorWfrp4e.applyDamage (wfrp4e.js:15646:84)
    at ChatWFRP._onApplyDamageClick (wfrp4e.js:4800:36)
    at HTMLElement.dispatch (jquery.min.js:2:40035)
    at v.handle (jquery.min.js:2:38006)<br/>**From**: woodelf_9<br/>foundry: 12.325<br/>wfrp4e: 7.1.6<br/>wfrp4e-core: 5.0.4<br/>wfrp4e-eis: 5.0.1<br/>wfrp4e-rnhd: 5.0.1<br/>wfrp4e-starter-set: 5.0.2<br/>Active Modules:

**Comment by chriss2023** [comment]
![chat log](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/147548129/14205240-3ef9-409e-8b2b-d4a089a3a1df)
