### ISSUE TITLE
[Up In Arms] Using Up in arms Critical  Hit Modifiers throws exception

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#2072]
I think this only happens if roll is >100

caught (in promise) TypeError: undefined. Cannot read properties of undefined (reading 'contents')
[Detected 1 package: system:wfrp4e]
    at WFRP_Tables._maxRange (wfrp4e.js:304:26)
    at WFRP_Tables.rollTable (wfrp4e.js:218:26)
    at async WFRP_Tables.formatChatRoll (wfrp4e.js:509:18)
    at async WFRP_Utility.handleTableClick (wfrp4e.js:7508:16)<br/>**From**: steven.evans<br/>foundry: 11.315<br/>wfrp4e: 7.2.0<br/>wfrp4e-core: 5.0.5<br/>wfrp4e-starter-set: 5.0.3<br/>wfrp4e-up-in-arms: 5.0.1<br/>Active Modules: filepicker-plus, lib-wrapper, module-credits, socketlib

**Comment by moo-man** [comment]
![image](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/28637157/e1f0b2a1-29c2-4243-b346-6103d347da89)
Cannot reproduce this, so I'll need more details on reproduction steps

**Comment by StevenEvans1966** [comment]
Try using the crit tables from Up in Arms

**Comment by moo-man** [comment]
That's what the screenshot is showing

**Comment by StevenEvans1966** [comment]
Has this been fixed?

**Comment by Forien** [comment]
> Has this been fixed?

If it was, the issue would be closed. Also there was no update released after 7.2.1. So no, it hasn't been fixed yet.
