### ISSUE TITLE
[WFRP4e System] I tried 12.330 and backed up to 11.315

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#2183]
I restored the backup made before versioning, but I get lot of errors in console:
in.js:16 Uncaught (in promise) TypeError: undefined. Cannot read properties of undefined (reading 'running')
[Detected 1 package: dice-so-nice(5.0.5)]
    at get canInteract [as canInteract] (main.js:16:220303)
    at HTMLBodyElement.<anonymous> (main.js:16:222882)
    at HTMLDocument.dispatch (jquery.min.js:2:43184)
    at y.handle (jquery.min.js:2:41168)
get canInteract @ main.js:16
(anonymous) @ main.js:16
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
20main.js:16 Uncaught (in promise) TypeError: undefined. Cannot read properties of undefined (reading 'running')
[Detected 1 package: dice-so-nice(5.0.5)]
    at get canInteract [as canInteract] (main.js:16:220303)
    at HTMLBodyElement.<anonymous> (main.js:16:222592)
    at HTMLDocument.dispatch (jquery.min.js:2:43184)
    at y.handle (jquery.min.js:2:41168)
get canInteract @ main.js:16
(anonymous) @ main.js:16
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
main.js:16 Uncaught TypeError: undefined. Cannot read properties of undefined (reading 'clearScene')
[Detected 1 package: dice-so-nice(5.0.5)]
    at Dice3D.resizeAndRebuild (main.js:16:221384)
    at Dice3D.resizeEnd (main.js:16:221303)
resizeAndRebuild @ main.js:16
resizeEnd @ main.js:16
setTimeout (async)
(anonymous) @ main.js:16
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
43main.js:16 Uncaught (in promise) TypeError: undefined. Cannot read properties of undefined (reading 'running')
[Detected 1 package: dice-so-nice(5.0.5)]
    at get canInteract [as canInteract] (main.js:16:220303)
    at HTMLBodyElement.<anonymous> (main.js:16:222592)
    at HTMLDocument.dispatch (jquery.min.js:2:43184)
    at y.handle (jquery.min.js:2:41168)
get canInteract @ main.js:16
(anonymous) @ main.js:16
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
main.js:16 Uncaught TypeError: undefined. Cannot read properties of undefined (reading 'clearScene')
[Detected 1 package: dice-so-nice(5.0.5)]
    at Dice3D.resizeAndRebuild (main.js:16:221384)
    at Dice3D.resizeEnd (main.js:16:221303)
resizeAndRebuild @ main.js:16
resizeEnd @ main.js:16
setTimeout (async)
(anonymous) @ main.js:16
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
479main.js:16 Uncaught (in promise) TypeError: undefined. Cannot read properties of undefined (reading 'running')
[Detected 1 package: dice-so-nice(5.0.5)]
    at get canInteract [as canInteract] (main.js:16:220303)
    at HTMLBodyElement.<anonymous> (main.js:16:222592)
    at HTMLDocument.dispatch (jquery.min.js:2:43184)
    at y.handle (jquery.min.js:2:41168)
get canInteract @ main.js:16
(anonymous) @ main.js:16
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
main.js:16 Uncaught TypeError: undefined. Cannot read properties of undefined (reading 'clearScene')
[Detected 1 package: dice-so-nice(5.0.5)]
    at Dice3D.resizeAndRebuild (main.js:16:221384)
    at Dice3D.resizeEnd (main.js:16:221303)
resizeAndRebuild @ main.js:16
resizeEnd @ main.js:16
setTimeout (async)
(anonymous) @ main.js:16
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
56main.js:16 Uncaught (in promise) TypeError: undefined. Cannot read properties of undefined (reading 'running')
[Detected 1 package: dice-so-nice(5.0.5)]
    at get canInteract [as canInteract] (main.js:16:220303)
    at HTMLBodyElement.<anonymous> (main.js:16:222592)
    at HTMLDocument.dispatch (jquery.min.js:2:43184)
    at y.handle (jquery.min.js:2:41168)
get canInteract @ main.js:16
(anonymous) @ main.js:16
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
main.js:16 Uncaught TypeError: undefined. Cannot read properties of undefined (reading 'clearScene')
[Detected 1 package: dice-so-nice(5.0.5)]
    at Dice3D.resizeAndRebuild (main.js:16:221384)
    at Dice3D.resizeEnd (main.js:16:221303)
resizeAndRebuild @ main.js:16
resizeEnd @ main.js:16
setTimeout (async)
(anonymous) @ main.js:16
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
77main.js:16 Uncaught (in promise) TypeError: undefined. Cannot read properties of undefined (reading 'running')
[Detected 1 package: dice-so-nice(5.0.5)]
    at get canInteract [as canInteract] (main.js:16:220303)
    at HTMLBodyElement.<anonymous> (main.js:16:222592)
    at HTMLDocument.dispatch (jquery.min.js:2:43184)
    at y.handle (jquery.min.js:2:41168)

Everything seems going wrong and can't do anything.
I tried to uninstall and reinstall, but nothing seems to change.
<br/>**From**: rporrini<br/>foundry: 11.315<br/>wfrp4e: 7.2.4<br/>wfrp4e-core: 5.0.7<br/>wfrp4e-eis: 5.0.3<br/>wfrp4e-rnhd: 5.0.2<br/>wfrp4e-starter-set: 5.0.3<br/>wfrp4e-ua1: 5.0.2<br/>Active Modules: arbron-context-menus, babele, chat-commander-wfrp4e, compendium-tools, dice-so-nice, drag-ruler, forien-armoury, foundryvtt-simple-calendar, lib-wrapper, mappa-reikland, module-credits, monks-bloodsplats, monks-chat-timer, monks-combat-details, monks-combat-marker, monks-hotbar-expansion, monks-player-settings, monks-sound-enhancements, monks-tokenbar, simple-dice-roller, smalltime, socketlib, soundfxlibrary, times-up, token-action-hud-core, token-action-hud-wfrp4e, token-attacher, torch, translation-core-it, trs-foundryvtt-dice-set, trs-metal-rainbow, vtta-tokenizer, weather-control, wfrp4e-eis-maps, wfrp4e-gm-toolkit, wfrp4e-it-translation-system7xx, wfrp4e-random-treasure, wfrp4e-rnhd-it, wfrp4e-starter-set-it, wfrp4e-ua1-it, wfrp4e-ubersreik-maps, _chatcommands

**Comment by moo-man** [comment]
Please troubleshoot in discord. Dumping logs is not a bug report
