### ISSUE TITLE
[Core Rulebook] Unable to Place Soulfire

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#2205]
Cast Soulfie with Prayer Granted.  Press Place Soulfire nothing happens.  I am seeing console error 

Uncaught (in promise) ReferenceError: undefined. effectData is not defined
[Detected 1 package: system:wfrp4e(8.0.2)]
    at ChatWFRP._onPlaceAreaEffect (wfrp4e.js:5349:101)
_onPlaceAreaEffect @ wfrp4e.js:5349
await in _onPlaceAreaEffect (async)
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
<br/>**From**: steven.evans<br/>foundry: 12.331<br/>wfrp4e: 8.0.2<br/>wfrp4e-core: 6.0.0<br/>Active Modules: filepicker-plus, lib-wrapper, module-credits, socketlib, warhammer-lib, wfrp4e-gm-toolkit

**Comment by StevenEvans1966** [comment]
can now place template after update to game system 8.0.3 but now get
VM828:6 Uncaught (in promise) TypeError: undefined. Cannot read properties of undefined (reading 'result')
[Detected 1 package: warhammer-lib(1.0.1)]
    at Object.eval (eval at execute (warhammer.js:319:21), <anonymous>:6:60)
    at WarhammerScript.execute (warhammer.js:319:121)
    at warhammer.js:957:73
    at Array.map (<anonymous>)
    at ActiveEffectWFRP4e.handleImmediateScripts (warhammer.js:957:62)
    at ActiveEffectWFRP4e._preCreate (warhammer.js:864:27)
    at async #preCreateDocumentArray (foundry-esm.js:56392:31)
    at async ClientDatabaseBackend._createDocuments (foundry-esm.js:56347:7)
    at async ActiveEffectWFRP4e.createDocuments (foundry-esm.js:11423:23)
    at async ActiveEffectWFRP4e.create (foundry-esm.js:11567:23)
    at async ActorWFRP4e.applyEffect (warhammer.js:4332:13)
    at async AreaHelpers.checkTokenAreaEffects (warhammer.js:3542:13)
    at async Semaphore._try (foundry-esm.js:6645:19)

**Comment by moo-man** [comment]
This I cannot reproduce, please make sure you're using an updated Soulfire item

**Comment by StevenEvans1966** [comment]
The error appears to be with applying the effect to the target.  If I place the template with no (enemy) tokens within it there is no error.  When I test using an orc (from Core rules) with in the template the error appears
