### ISSUE TITLE
[WFRP4e System] Cannot open character sheet

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#2223]
I am unable to open one of my character sheets, even though I can open the other three. I do not know exactly what the problem is. 

Using the console I can see the following issues:

Error: An error occurred while rendering ActorSheetWFRP4eCharacter 246. Cannot read properties of undefined (reading 'toLowerCase')
    at Hooks.onError (foundry.js:654:24)
    at foundry.js:5795:13
onError @ foundry.js:655
foundry.js:6347 Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
    at ActorSheetWFRP4eCharacter.setPosition (foundry.js:6347:27)
    at _onWindowResize (foundry.js:10352:13)<br/>**From**: _christurner<br/>foundry: 12.331<br/>wfrp4e: 8.0.3<br/>wfrp4e-core: 6.0.0<br/>wfrp4e-eis: 6.0.0<br/>wfrp4e-starter-set: 6.0.0<br/>wfrp4e-ua1: 6.0.0<br/>Active Modules: dice-so-nice, warhammer-lib, wfrp4e-gm-toolkit, wfrp4e-ubersreik-maps

**Comment by moo-man** [comment]
malformed career data
