### ISSUE TITLE
[WFRP4e System] skill xp modifier broken

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#2228]
After manually changing the XP modifier on a skill the character sheet won't open
Example: The character has the talent Witch! so I modified Language (Magick) xp modifier to -5, after doing that it won't open anymore, I've tried with other skills same thing happnes

Got this two eerrors on console:

foundry.js:655 Error: An error occurred while rendering ActorSheetWFRP4eCharacter 72. Cannot read properties of undefined (reading 'toLowerCase')
[Detected 2 packages: system:wfrp4e(8.0.4), warhammer-lib(1.0.2)]
    at Hooks.onError (foundry.js:654:24)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:507:22)
    at 🎁Hooks.onError#lib-wrapper (listeners.js:140:11)
    at 🎁Hooks.onError#0 (libWrapper-wrapper.js:187:52)
    at foundry.js:5795:13

warhammer.js:323 Script Add Language (Magick) threw error: ReferenceError: actor is not defined.
 Context and Arguments: Object Object<br/>**From**: akygat<br/>foundry: 12.331<br/>wfrp4e: 8.0.4<br/>wfrp4e-altdorf: 6.0.0<br/>wfrp4e-archives1: 6.0.0<br/>wfrp4e-archives2: 6.0.0<br/>wfrp4e-core: 6.0.0<br/>wfrp4e-dotr: 6.0.0<br/>wfrp4e-eis: 6.0.0<br/>wfrp4e-horned-rat: 6.0.0<br/>wfrp4e-lustria: 6.0.0<br/>wfrp4e-middenheim: 6.0.0<br/>wfrp4e-pbtt: 6.0.0<br/>wfrp4e-rnhd: 6.0.0<br/>wfrp4e-salzenmund: 6.0.0<br/>wfrp4e-soc: 6.0.0<br/>wfrp4e-starter-set: 6.0.0<br/>wfrp4e-ua1: 6.0.0<br/>wfrp4e-up-in-arms: 6.0.0<br/>wfrp4e-wom: 6.0.0<br/>wfrp4e-zoo: 6.0.0<br/>Active Modules: aedifs-tactical-grid, autoanimations, chat-commander-wfrp4e, chat-images, color-picker, colorsettings, combat-tracker-dock, dice-calculator, dice-so-nice, forien-armoury, foundryvtt-simple-calendar, fxmaster, healthEstimate, image-hover, JB2A_DnD5e, levels, lib-wrapper, pdf-pager, popout, potato-or-not, sequencer, settings-extender, socketlib, splatter, theripper-premium-hub, times-up, token-action-hud-core, token-action-hud-wfrp4e, token-frames, vtta-tokenizer, wall-height, warhammer-lib, wfrp4e-character-details, wfrp4e-gm-toolkit, your-turn, _chatcommands

**Comment by moo-man** [comment]
Issue is resolved, but your data is corrupted from before the update.
