### ISSUE TITLE
[WFRP4e System] Ammunition qualities are no longer transfered to weapons

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#2245]
For example: Bullet and Powder no longer gives a pistol Impale and Penetrating when selected. 

Also, could be related, but Acurate gives a "script" button in the trappings tab, which throws an error:

warhammer.js:5768 Uncaught TypeError: Cannot read properties of null (reading 'manualScripts')
    at ActorSheetWFRP4eCharacter._onTriggerScript (warhammer.js:5768:29)
    at HTMLFormElement.dispatch (jquery.min.js:2:40035)
    at v.handle (jquery.min.js:2:38006)<br/>**From**: The First#7330<br/>foundry: 12.331<br/>wfrp4e: 8.1.0<br/>wfrp4e-core: 6.0.1<br/>Active Modules: warhammer-lib

**Comment by moo-man** [comment]
![image](https://github.com/user-attachments/assets/f3f877ea-8097-451f-bdb9-5719f13a3da3)
Can't reproduce this.

**Comment by moo-man** [comment]
Oh, it only adds if you don't have the skill as in the screenshot.
