### ISSUE TITLE
[WFRP4e System] One Players's Character sheet keeps failing to open

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#2262]
One player has on multiple occasions had their character sheet fail to even open a window where it should be. The only fix has been to restore from back up. We have made new characters, new profiles for him and we ALWAYS get the same issue back. Please help.

ndry VTT | Rendering ActorSheetWFRP4eCharacter
foundry.js:655 Error: An error occurred while rendering ActorSheetWFRP4eCharacter 33. One of original or other are not Objects!
    at Hooks.onError (foundry.js:654:24)
    at foundry.js:5795:13
onError @ foundry.js:655
(anonymous) @ foundry.js:5795
Promise.catch (async)
render @ foundry.js:5793
_onClickLeft2 @ foundry.js:61477
callback @ foundry.js:30834
#handleClickLeft2 @ foundry.js:31057
#handleLeftDown @ foundry.js:31016
#handlePointerDown @ foundry.js:30981
notifyListeners @ EventBoundary.ts:1454
notifyTarget @ EventBoundary.ts:662
propagate @ EventBoundary.ts:299
dispatchEvent @ EventBoundary.ts:210
mapPointerDown @ EventBoundary.ts:683
mapEvent @ EventBoundary.ts:231
onPointerDown @ EventSystem.ts:373<br/>**From**: Vzmis#8275<br/>foundry: 12.331<br/>wfrp4e: 8.1.3<br/>Active Modules: warhammer-lib

**Comment by moo-man** [comment]
Old issue that has since been resolved but your data is still corrupted, contacted on Discord
