### ISSUE TITLE
[WFRP4e System] Placing template of Test Independent Area effect throws an error

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#2280]
```
warhammer.js:3507 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'effects')
[Detected 1 package: warhammer-lib(1.1.1)]
    at warhammer.js:3507:139
    at Array.filter (<anonymous>)
    at AreaHelpers.checkAreaCreate (warhammer.js:3507:59)
    at #call (foundry.js:632:20)
    at Hooks.callAll (foundry.js:589:17)
    at foundry-esm.js:56440:17
    at foundry-esm.js:56445:43
    at Array.map (<anonymous>)
    at #handleCreateDocuments (foundry-esm.js:56445:33)
    at async MeasuredTemplateDocument.createDocuments (foundry-esm.js:11423:23)
    at async ActorSheetWFRP4eCharacter._onPlaceAreaEffect (warhammer.js:5853:9)
```

will provide screenshots in comments

<br/>**From**: forien<br/>foundry: 12.331<br/>wfrp4e: 8.2.0<br/>wfrp4e-altdorf: 6.0.1<br/>wfrp4e-archives1: 6.0.1<br/>wfrp4e-archives2: 6.0.1<br/>wfrp4e-archives3: 6.0.0<br/>wfrp4e-core: 6.0.1<br/>wfrp4e-dotr: 6.0.1<br/>wfrp4e-eis: 6.0.2<br/>wfrp4e-lustria: 6.0.1<br/>wfrp4e-middenheim: 6.0.2<br/>wfrp4e-owb2: 6.0.1<br/>wfrp4e-pbtt: 6.0.0<br/>wfrp4e-rnhd: 6.0.2<br/>wfrp4e-salzenmund: 6.0.1<br/>wfrp4e-soc: 6.0.2<br/>wfrp4e-starter-set: 6.0.1<br/>wfrp4e-up-in-arms: 6.0.2<br/>wfrp4e-wom: 6.0.2<br/>wfrp4e-zoo: 6.0.0<br/>Active Modules: ATL, JB2A_DnD5e, _CodeMirror, _chatcommands, autoanimations, chat-commander-wfrp4e, colorsettings, custom-css, darkraven-games-soundscapes-free, dfreds-chat-pins, dfreds-effects-panel, dice-so-nice, drag-ruler, entice-with-dice-so-nice, forien-actors-summary, forien-ammo-swapper, forien-armoury, forien-copy-environment, forien-custom-utility, forien-easy-polls, forien-quest-log, forien-test-utilities, forien-unidentified-items, foundryvtt-simple-calendar, image-hover, item-piles, ivan-duch-music-packs, levels, lib-wrapper, light-switch, local-shared-compendiums, michaelghelfi, monks-hotbar-expansion, moulinette-core, moulinette-imagesearch, moulinette-scenes, moulinette-tiles, multi-token-edit, permission_viewer, polyglot, popout, quick-insert, remote-highlight-ui, sequencer, socketlib, soundfxlibrary, stairways, sweetnothings, tabletop-rpg-music, times-up, token-action-hud-core, token-action-hud-wfrp4e, token-ease, token-variants, token-z, trs-foundryvtt-dice-set, trs-metal-rainbow, update-your-password, wall-height, warhammer-lib, wfrp4e-dotr-maps, wfrp4e-gm-toolkit

**Comment by moo-man** [comment]
can't reproduce this, but I assume that's just because I've added a fix for it since this was posted.
